version: "3.1"

services:

    db:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: pwakey
            POSTGRES_USER: pwdauser
            POSTGRES_DB: pwd
        volumes:
            - ./data/pgdata/postgres:/var/lib/postgresql/data:delegated
        ports:
            - '5432:5432'

    app:
        image: yiisoftware/yii2-php:8.1-apache
        volumes: 
            - ./src/composer/cache:/root/.composer/cache:delegated
            - ./src/basic:/app:delegated
        environment: 
            DB_DATABASE: pwd
            DB_PASSWORD: pwakey
            DB_USER: pwdauser
            DB_HOST: db
            PHP_USER_ID: 501
            
        ports: 
            - 8000:80
   
   

            